services:
  spring:
    build: .
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pg:5432/turkcellbootcamppair1db
  pg:
    image: postgres:16.2-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=postgres
    volumes:
      - turkcell-postgresql:/var/lib/postgresql/data


volumes:
  turkcell-postgresql:
    name: turkcell-postgresql